import { useQuery, useMutation } from "@tanstack/react-query";

const noop = () => {};
const emptyQuery = (key: string) => () =>
  useQuery({ queryKey: [key], queryFn: async () => ({}) as any, enabled: false });
const emptyMutation = () => () => useMutation({ mutationFn: async () => ({}) as any });
const queryKeyFn = (key: string) => () => [key];

export const useGetDashboardSummary = emptyQuery("dashboard-summary");
export const useGetDashboardUpcomingShifts = emptyQuery("dashboard-upcoming-shifts");
export const useGetDashboardComplianceOverview = emptyQuery("dashboard-compliance");
export const useListParticipants = emptyQuery("participants");
export const useListStaff = emptyQuery("staff");
export const useListShifts = emptyQuery("shifts");
export const useListIncidents = emptyQuery("incidents");
export const useListCaseNotes = emptyQuery("case-notes");
export const useListInvoices = emptyQuery("invoices");
export const useListServiceAgreements = emptyQuery("service-agreements");
export const useGetParticipant = emptyQuery("participant");
export const useGetParticipantGoals = emptyQuery("participant-goals");
export const useGetParticipantContacts = emptyQuery("participant-contacts");
export const useGetStaff = emptyQuery("staff-detail");
export const useGetStaffCompliance = emptyQuery("staff-compliance");
export const useGetStaffAvailability = emptyQuery("staff-availability");
export const useCreateParticipant = emptyMutation();
export const useDeleteParticipant = emptyMutation();
export const useUpdateParticipant = emptyMutation();
export const useCreateStaff = emptyMutation();
export const useDeleteStaff = emptyMutation();
export const useUpdateStaff = emptyMutation();
export const useCreateShift = emptyMutation();
export const useDeleteShift = emptyMutation();
export const useUpdateShift = emptyMutation();
export const useCreateIncident = emptyMutation();
export const useCreateCaseNote = emptyMutation();
export const useDeleteCaseNote = emptyMutation();
export const useCreateServiceAgreement = emptyMutation();
export const getListParticipantsQueryKey = queryKeyFn("participants");
export const getListStaffQueryKey = queryKeyFn("staff");
export const getListShiftsQueryKey = queryKeyFn("shifts");
export const getListIncidentsQueryKey = queryKeyFn("incidents");
export const getListCaseNotesQueryKey = queryKeyFn("case-notes");
export const getListInvoicesQueryKey = queryKeyFn("invoices");
export const getListServiceAgreementsQueryKey = queryKeyFn("service-agreements");
export const getGetParticipantQueryKey = queryKeyFn("participant");
export const getGetParticipantGoalsQueryKey = queryKeyFn("participant-goals");
export const getGetStaffQueryKey = queryKeyFn("staff-detail");
export const getGetStaffComplianceQueryKey = queryKeyFn("staff-compliance");
export const setAuthTokenGetter: (fn: () => string | null) => void = noop;
